from __future__ import annotations

TOPIC_MAP_V2 = "TOPIC_MAP_V2"
SEO_PLANNER_V2 = "SEO_PLANNER_V2"
HEADING_PLANNER_V2 = "HEADING_PLANNER_V2"
CONTENT_GENERATOR_V2 = "CONTENT_GENERATOR_V2"
SEO_VALIDATOR_V2 = "SEO_VALIDATOR_V2"
REVISION_V2 = "REVISION_V2"
EXISTING_CONTENT_V2 = "EXISTING_CONTENT_V2"
PLANNING_BUNDLE_V2 = "PLANNING_BUNDLE_V2"

PROMPT_VERSIONS = {
    "TOPIC_MAP": TOPIC_MAP_V2,
    "SEO_PLANNER": SEO_PLANNER_V2,
    "HEADING_PLANNER": HEADING_PLANNER_V2,
    "CONTENT_GENERATOR": CONTENT_GENERATOR_V2,
    "SEO_VALIDATOR": SEO_VALIDATOR_V2,
    "REVISION": REVISION_V2,
    "EXISTING_CONTENT": EXISTING_CONTENT_V2,
    "PLANNING_BUNDLE": PLANNING_BUNDLE_V2,
}
